---
name: Release Project Air

# This job is meant to be dispatched when a release is published. It shall update the CHANGELOGs.
on:
  release:
    types: [published]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        repository:
          - labs-air
          - labs-air-charts
          - labs-air-contrib
          - labs-air-edgex
          - labs-air-infra
          - labs-air-services
          - labs-air-ui
          - labs-lightcrane-contrib
          - labs-lightcrane-services

    permissions:
      contents: write
    steps:
      - name: Checkout ${{ matrix.repository }} for the event ${{ github.event_name }} release ${{ github.event.release.tag_name }}
        uses: actions/checkout@v2
        with:
          repository: TIBCOSoftware/${{ matrix.repository }}
          token: ${{ secrets.LABS_ACTIONS_ACCESS_TOKEN }}
          path: .github/${{ matrix.repository }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules for the ${{ matrix.repository }} repository
        uses: actions/cache@v2
        id: cache
        with:
          path: .github/${{ matrix.repository }}/node_modules
          key: ${{ runner.os }}-cicd-${{ matrix.repository }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cicd-${{ matrix.repository }}-

      - name: Set up the node modules
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: .github/${{ matrix.repository }}
        run: |
          npm ci

      - name: Update the changelog for the release ${{ github.event.release.tag_name }}
        working-directory: .github/${{ matrix.repository }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm run release -- --release-as "${{ github.event.release.tag_name }}"
          DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
          git push --follow-tags origin "${DEFAULT_BRANCH}"

